---
homebrew_repositories: []

homebrew_packages:
  - ansible
  - awscli
  - coreutils
  - curl
  - docker
  - ghq
  - gibo
  - git
  - glide
  - go
  - jq
  - nvm
  - { name: openssl, state: linked, install_options: force }
  - packer
  - peco
  - pyenv-virtualenv
  - python
  - rbenv
  - ruby-build
  - terraform
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - wget
