#
# install brew
#
- name: update brew
  register: result
  ignore_errors: True
  command: >
    brew update

- name: get brew installer
  get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/brew_install
  when: result|failed

- name: proceed brew installer
  command: >
    ruby /tmp/brew_install
  when: result|failed

#
# install apps
#
- name: tap external homebrew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_repositories}}"
  when: "{{homebrew_repositories}}"
  become: no

- name: update homebrew
  homebrew: update_homebrew=yes
  become: no

- name: install and upgrade homebrew packages
  homebrew:
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{homebrew_packages}}"
  when: "{{homebrew_packages}}"
  become: no

- name: create bin directory for golang
  file: name=~/bin state=directory

- name: create pkg directory for golang
  file: name=~/pkg state=directory

- name: create src directory for golang
  file: name=~/src state=directory
